### ISSUE TITLE
TypeError: Object of type PosixPath is not JSON serializable

### ISSUE THREAD

**Issue by moritzschaefer** [proofit404/service-factory#3]
In spacemacs, anaconda-mode fails because service_factory crashes throws an Exception:

I'm not sure, which package is responsible, so I start here.

`Exception happened during processing of request from ('127.0.0.1', 46218)
Traceback (most recent call last):
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/moritz/.emacs.d/.cache/anaconda-mode/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/moritz/.emacs.d/.cache/anaconda-mode/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 51, in __call__
    response = self.make_response(args, result)
  File "/home/moritz/.emacs.d/.cache/anaconda-mode/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 112, in make_response
    return dumps({
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
`

**Comment by moritzschaefer** [comment]
An update to my NixOS system fixed the error!
